language: generic

env:
  - FLUTTER_BUILD_RELEASE_CHANNEL=stable

matrix:
  include:
    - name: iOS Build
      os: osx
      language: generic
      osx_image: xcode12.4
      before_script:
        - echo -e "machine github.com\n  login $GITHUB_TOKEN" >> ~/.netrc # match 인증서 저장소에 접근하기 위해 GitHub Token 설치

        - git clone https://github.com/flutter/flutter.git -b stable
        - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH

        - gem install bundler
        - gem install cocoapods
        - cd ios && bundle install && cd ..

      script:
        - flutter doctor -v # 빌드 디버깅을 위한 Flutter 정보 로깅

        - flutter build ios --no-codesign --build-number=$TRAVIS_BUILD_NUMBER # Flutter iOS 빌드에 필요한 파일을 내려받고 번들의 빌드 이름 및 빌드 번호 설정

        - cd ios
        - bundle exec fastlane beta # fastlane을 사용한 코드 사이닝, 빌드 및 TestFligth 배포

    - name: Android Build
      language: android
#      android:
#        components:
#          - build-tools-29.0.3
#          - android-29
      before_install:
        - yes | sdkmanager "platforms;android-29" # components 29 version issue로 sdkmanager 이용
        - yes | sdkmanager "build-tools;29.0.3"
        - rvm install 2.7.2
        - openssl aes-256-cbc -K $encrypted_3b9f0b9d36d1_key -iv $encrypted_3b9f0b9d36d1_iv -in secrets.tar.enc -out secrets.tar -d
      before_script:
        - tar xvf secrets.tar
        - git clone https://github.com/flutter/flutter.git -b stable
        - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
        - gem install bundler && cd android && bundle install && cd ..
      script:
        - flutter doctor -v # 빌드 디버깅을 위한 Flutter 정보 로깅
        - flutter build appbundle --build-number=$TRAVIS_BUILD_NUMBER # App Bundle 빌드
        - cd android
        - bundle exec fastlane beta # fastlane을 이용해 빌드 파일 업로드